### ISSUE TITLE
Adding RegExp support on the color rules

### ISSUE THREAD

**Issue by burnersk** [burnersk/Dancer2-Logger-Console-Colored#1]
Feature request from @ambs

> Are you planning on adding regexp support on the color rules?
> 
> It would be nice to have 404 (routes not existing) appear in red or
> something like that...

**Comment by ambs** [comment]
weeeeee.

**Comment by burnersk** [comment]
@ambs it's a *little* delayed but here it is ;)

**Comment by simbabque** [comment]
@ambs I realize I'm late to the party, but I was just looking into the module to fix a bug and I think we can add this, too. Did you have anything in mind in terms of interface two years ago? I have a vague idea of how this could work, but don't see how exactly that would be useful.

**Comment by ambs** [comment]
Something like:

``````
    colored_regex:
      - re: /404/
        color: 'some_color_definition'
      - re: /missing/
        color: 'some_other_color'
``````````
Just an option. Given @burnersk is the original author, maybe he has other preferences.
